### ISSUE TITLE
support margin 

### ISSUE THREAD

**Issue by danywheeler** [twolfson/layout#8]
in css sprite we need x and y to be able add margin for it to solve div background edge shows other image. 

[https://github.com/sprity/sprity/issues/29](url)  sprity issue.

**Comment by twolfson** [comment]
We handle this in `spritesmith` by pre-padding the widths/heights. This allows for custom gravity and removes complication from the `layout` library:

https://github.com/Ensighten/spritesmith/blob/3.1.0/src/smith.js#L127-L134

https://github.com/Ensighten/spritesmith/blob/3.1.0/src/smith.js#L148-L153
